# Why is eggs a valid variable name while 100 is invalid?
# ANSWER: EGGS IS A VALID VARIABLE AS IT STARTS WITH A LETTER, NUMBERS CANNOT BE USED TO NAME A VARIABLE, ONLY IF IT IS AT THE END OF THE VARIABLE NAME, NOT AT THE BEGINNING.

# Author: Eva Czeyda-Pommersheim